Repository gongmoja/gongmoja, pull requests merged in 2023-08, with the labels that each got.

#17 feat : added ChatService with joinChat and createChatRoom
  gongmoja/src/main/java/com/est/gongmoja/dto/ChatDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatDataResponseDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatRoomDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatRoomResponseDto.java
  gongmoja/src/main/java/com/est/gongmoja/entity/CalendarEntity.java
  gongmoja/src/main/java/com/est/gongmoja/entity/ChatRoomEntity.java
  gongmoja/src/main/java/com/est/gongmoja/entity/StockEntity.java
  gongmoja/src/main/java/com/est/gongmoja/repository/ChatDataRepository.java
  gongmoja/src/main/java/com/est/gongmoja/repository/ChatRoomRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/ChatService.java
  gongmoja/src/main/java/com/est/gongmoja/service/StockService.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
Labels: 🛠️feature, 🔁refactor, ❗️style

#20 feat : jwtTokenUtils 구현 및 auth 관련 skeleton 생성
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/config/PasswordConfig.java
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/user/UserRegisterRequestDto.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenUtil.java
  gongmoja/src/main/java/com/est/gongmoja/repository/UserRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
Labels: 🛠️feature

#21 feat: 크롤링 데이터 parsing, DB 저장
  gongmoja/src/main/java/com/est/gongmoja/entity/StockEntity.java
  gongmoja/src/main/java/com/est/gongmoja/repository/StockRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
Labels: 🛠️feature

#26 feat : 예외처리 관련 코드 통일
  gongmoja/src/main/java/com/est/gongmoja/exception/CustomException.java
  gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
  gongmoja/src/main/java/com/est/gongmoja/exception/ExceptionManager.java
Labels: 🧹chore

#27 fix: NewsCrawlingService, NewsEntity 수정
  gongmoja/src/main/java/com/est/gongmoja/entity/NewsEntity.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
Labels: 🛠️feature, 🔁refactor

#36 feat : Answer 기능 추가, Question 단일조회기능 추가
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/Calendar/CalendarController
  gongmoja/src/main/java/com/est/gongmoja/Calendar/CalendarService
  gongmoja/src/main/java/com/est/gongmoja/controller/.controller
  gongmoja/src/main/java/com/est/gongmoja/controller/AnswerController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/CalendarController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/answer/AnswerFormDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/question/QuestionFormDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/question/QuestionRequestDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/user/UserDto.java
  gongmoja/src/main/java/com/est/gongmoja/entity/AnswerEntity.java
  gongmoja/src/main/java/com/est/gongmoja/entity/QuestionEntity.java
  gongmoja/src/main/java/com/est/gongmoja/exception/DataNotFoundException.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/.jwt
  gongmoja/src/main/java/com/est/gongmoja/repository/.repo
  gongmoja/src/main/java/com/est/gongmoja/repository/AnswerRepository.java
  gongmoja/src/main/java/com/est/gongmoja/repository/CalendarRepository.java
  gongmoja/src/main/java/com/est/gongmoja/repository/QuestionImageRepository.java
  gongmoja/src/main/java/com/est/gongmoja/repository/QuestionRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/AnswerService.java
  gongmoja/src/main/java/com/est/gongmoja/service/CalendarService.java
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/resources/static/question/bootstrap.min.css
  gongmoja/src/main/resources/static/question/bootstrap.min.js
  gongmoja/src/main/resources/templates/answer/answer_form.html
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/question/layout.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
  gongmoja/src/main/resources/templates/question/question_list.html
  gongmoja/src/test/java/com/est/gongmoja/QuestionTests.java
Labels: 🛠️feature, 🔁refactor, ❗️style

#34 feat : 로그아웃 로직 구현 , jwt Filter 구현
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/config/CustomLogoutHandler.java
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/entity/RefreshTokenEntity.java
  gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenUtil.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
  gongmoja/src/main/resources/templates/mypage.html
Labels: 🛠️feature, 🔁refactor

#39 feat : fullcalendar, calendar 기능 수정
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/controller/CalendarController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/question/QuestionFormDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/question/QuestionRequestDto.java
  gongmoja/src/main/java/com/est/gongmoja/entity/QuestionEntity.java
  gongmoja/src/main/java/com/est/gongmoja/repository/CalendarRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/CalendarService.java
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/calendar/calendarPage.html
  gongmoja/src/main/resources/templates/calendar/fullcalendar-5.11.5/main.css
  gongmoja/src/main/resources/templates/calendar/fullcalendar-5.11.5/main.js
  gongmoja/src/main/resources/templates/question/layout.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
  gongmoja/src/main/resources/templates/question/question_list.html
Labels: 🛠️feature, ❗️style

#42 feat : OAuth2 백엔드 로직
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/config/CustomLogoutHandler.java
  gongmoja/src/main/java/com/est/gongmoja/config/WebConfig.java
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/AnswerController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatRoomDto.java
  gongmoja/src/main/java/com/est/gongmoja/entity/ChatRoomEntity.java
  gongmoja/src/main/java/com/est/gongmoja/entity/UserEntity.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2User.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/KakaoOAuth2User.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/NaverOAuth2User.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2FailureHandler.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2UserInfo.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2UserInfoFactory.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
Labels: 🛠️feature, 🧹chore

#46 feat: Sponsor repo 생성
  gongmoja/src/main/java/com/est/gongmoja/entity/SponsorEntity.java
  gongmoja/src/main/java/com/est/gongmoja/entity/StockEntity.java
  gongmoja/src/main/java/com/est/gongmoja/repository/SponsorRepository.java
Labels: 🛠️feature, ✅test

#47 feat: 경쟁률 크롤링 기초 구현
  gongmoja/src/main/java/com/est/gongmoja/entity/CompetitionEntity.java
  gongmoja/src/main/java/com/est/gongmoja/repository/CompetitionRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/CompetitonCrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/SponsorService.java
Labels: 🛠️feature, ✅test

#51 feat : OAuth2 구현
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/config/AppProperties.java
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/api/SocialUserController.java
  gongmoja/src/main/java/com/est/gongmoja/entity/UserEntity.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/CookieUtil.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
  gongmoja/src/main/resources/templates/users/login.html
Labels: 🛠️feature, 🐞bug

#55 feat : oauth2.0 구현 및 리팩터링
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/config/AppProperties.java
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/api/SocialUserController.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/CookieUtil.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/KakaoOAuth2User.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
  gongmoja/src/main/resources/templates/main.html
Labels: 🛠️feature, 🔁refactor

#61 feat : 질문 게시판 User 정보 연동 및 이미지 업로드 기능 수정
  gongmoja/src/main/java/com/est/gongmoja/controller/CalendarController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/question/QuestionFormDto.java
  gongmoja/src/main/java/com/est/gongmoja/repository/QuestionRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
  gongmoja/src/main/resources/static/fullcalendar-5.11.5/main.css
  gongmoja/src/main/resources/static/fullcalendar-5.11.5/main.js
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/calendar/calendarPage.html
  gongmoja/src/main/resources/templates/graph.html
  gongmoja/src/main/resources/templates/main.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
  gongmoja/src/main/resources/templates/question/question_list.html
  gongmoja/src/test/java/com/est/gongmoja/QuestionTests.java
Labels: 🛠️feature, 🔁refactor, ❗️style, 🪛fix

#64 feat: 캘린더 DB 연동
  gongmoja/src/main/java/com/est/gongmoja/controller/CalendarController.java
  gongmoja/src/main/java/com/est/gongmoja/service/CalendarService.java
  gongmoja/src/main/java/com/est/gongmoja/service/RedisService.java
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/calendar/calendarPage.html
Labels: 🛠️feature, ❗️style

#69 feat: calendar 일정 클릭시 페이지 이동 구현
  gongmoja/src/main/java/com/est/gongmoja/service/CalendarService.java
  gongmoja/src/main/resources/templates/calendar/calendar.html
Labels: 🛠️feature

#73 fix : 소셜로그인 시 JSESSIONID 쿠키 남는 에러
  gongmoja/src/main/java/com/est/gongmoja/config/CustomLogoutHandler.java
  gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/CookieUtil.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
Labels: 🪛fix

#75 refactor : 소셜로그인 일부 로직 수정 , 로그인 로그아웃 프론트 연결
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/WebController.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
  gongmoja/src/main/resources/static/bootstrap/img/btn_kakao.svg
  gongmoja/src/main/resources/static/bootstrap/img/btn_naver.svg
  gongmoja/src/main/resources/templates/forgot-password.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/register.html
  gongmoja/src/main/resources/templates/users/forgot-password.html
  gongmoja/src/main/resources/templates/users/login.html
  gongmoja/src/main/resources/templates/users/register.html
Labels: 🔁refactor, 🪛fix

#76 feat: 마이페이지 매핑
  gongmoja/src/main/java/com/est/gongmoja/controller/FavoriteController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/repository/QuestionRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/resources/static/bootstrap/vendor/fontawesome-free/svgs/solid/comment.svg
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/mypage.html
Labels: 🛠️feature, ✅test

#77 style : 부트스트랩 메인페이지 수정, 질문게시판 수정
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/entity/QuestionEntity.java
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/resources/static/bootstrap/css/sb-admin-2.css
  gongmoja/src/main/resources/static/bootstrap/vendor/jquery/jquery.js
  gongmoja/src/main/resources/static/questionFiles/unte140@naver.com/79d5a264-8733-4034-bf99-05c48055a1c0_projec2_readme.PNG
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/index1.html
  gongmoja/src/main/resources/templates/main.html
  gongmoja/src/main/resources/templates/question/question_detail.html
Labels: ❗️style
