Repository gongmoja/gongmoja, pull requests merged in 2023-09, with the labels that each got.

#79 feat : email 통한 비밀번호 재발급
  gongmoja/build.gradle
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/user/UserForgotPasswordRequestDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/user/UserModifyPasswordRequestDto.java
  gongmoja/src/main/java/com/est/gongmoja/entity/Role.java
  gongmoja/src/main/java/com/est/gongmoja/entity/UserEntity.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
  gongmoja/src/main/java/com/est/gongmoja/repository/UserRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/MailService.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
  gongmoja/src/main/resources/templates/temp-password.html
  gongmoja/src/main/resources/templates/users/forgot-password.html
Labels: 🛠️feature

#83 feat: 메인페이지 스크롤 구현
  gongmoja/src/main/java/com/est/gongmoja/controller/ChatController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/FavoriteController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/StockController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatDataDto.java
  gongmoja/src/main/java/com/est/gongmoja/dto/chat/ChatRoomResponseDto.java
  gongmoja/src/main/java/com/est/gongmoja/entity/ChatDataEntity.java
  gongmoja/src/main/java/com/est/gongmoja/entity/ChatRoomEntity.java
  gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
  gongmoja/src/main/java/com/est/gongmoja/repository/UserRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/ChatService.java
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/java/com/est/gongmoja/service/NewsCrawlingService.java
  gongmoja/src/main/resources/templates/index.html
Labels: 🛠️feature, ❗️style

#84 feat : QuestionController user정보 넘기기, 내비게이션 바 수정
  gongmoja/src/main/java/com/est/gongmoja/controller/AnswerController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/resources/static/fullcalendar-5.11.5/main.css
  gongmoja/src/main/resources/static/fullcalendar-5.11.5/main.js
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/mypage.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
  gongmoja/src/main/resources/templates/question/question_list.html
  gongmoja/src/main/resources/templates/stock/stock.html
Labels: 🛠️feature, ❗️style

#85 chore: ipoDate 예외처리
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
Labels: 🔁refactor, 🧹chore, 🐞bug

#94 fix: 스크롤 이벤트 div 변경
  gongmoja/src/main/resources/templates/index.html
Labels: 🛠️feature, 🐞bug, 🪛fix

#96 style : 페이지 타이틀 및 footer 추가
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/resources/templates/chat/chat-room.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/mypage.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
  gongmoja/src/main/resources/templates/question/question_list.html
  gongmoja/src/main/resources/templates/stock/stock.html
Labels: ❗️style, 🪛fix

#97 feat : 어드민 페이지 + 비밀번호 변경 로직 추가
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/AdminController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/QuestionController.java
  gongmoja/src/main/java/com/est/gongmoja/controller/WebController.java
  gongmoja/src/main/java/com/est/gongmoja/entity/RefreshTokenEntity.java
  gongmoja/src/main/java/com/est/gongmoja/jwt/JwtTokenFilter.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/CustomOAuth2UserService.java
  gongmoja/src/main/java/com/est/gongmoja/oauth2/OAuth2SuccessHandler.java
  gongmoja/src/main/java/com/est/gongmoja/repository/RefreshTokenRepository.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
  gongmoja/src/main/resources/templates/mypage.html
  gongmoja/src/main/resources/templates/users/modify-password.html
Labels: 🛠️feature

#98 chore: 전체적인 요소 사이즈 수정
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/resources/templates/404.html
  gongmoja/src/main/resources/templates/500.html
  gongmoja/src/main/resources/templates/error.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/stock/stock.html
  gongmoja/src/main/resources/templates/users/modify-password.html
Labels: 🔁refactor, ❗️style, 🧹chore

#102 feat : 마이페이지 버튼 ROLE 적용, 스타일 변경
  gongmoja/src/main/java/com/est/gongmoja/service/CrawlingService.java
  gongmoja/src/main/resources/templates/chat/chat-room.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/mypage.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
  gongmoja/src/main/resources/templates/question/question_list.html
  gongmoja/src/main/resources/templates/question/question_list_admin.html
  gongmoja/src/main/resources/templates/stock/stock.html
  gongmoja/src/main/resources/templates/users/modify-password.html
Labels: 🛠️feature, ❗️style

#103 refactor : Security Configuration 로직 수정 + 비밀번호 변경 로직 보완
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/exception/ErrorCode.java
  gongmoja/src/main/java/com/est/gongmoja/service/UserService.java
  gongmoja/src/main/resources/templates/mypage.html
Labels: 🛠️feature, 🔁refactor

#109 feat : 파일업로드시에만 첨부파일 확인 가능하게 변경
  gongmoja/src/main/java/com/est/gongmoja/service/QuestionService.java
  gongmoja/src/main/resources/templates/question/question_detail.html
Labels: 🛠️feature

#112 feat : 파일업로드 형식 제한 추가
  gongmoja/src/main/resources/templates/calendar/calendar.html
  gongmoja/src/main/resources/templates/index.html
  gongmoja/src/main/resources/templates/mypage.html
  gongmoja/src/main/resources/templates/question/question_detail.html
  gongmoja/src/main/resources/templates/question/question_form.html
Labels: 🛠️feature

#114 fix : 회원가입 로직 수정
  gongmoja/src/main/java/com/est/gongmoja/config/WebSecurityConfig.java
  gongmoja/src/main/java/com/est/gongmoja/controller/UserController.java
  gongmoja/src/main/java/com/est/gongmoja/dto/user/UserRegisterRequestDto.java
  gongmoja/src/main/resources/templates/users/message.html
  gongmoja/src/main/resources/templates/users/register.html
Labels: 🪛fix

#118 refactor : 비밀변경 수정로직 리팩토링
  src/main/java/com/est/gongmoja/controller/UserController.java
Labels: 🔁refactor

#119 refactor : 회원가입 로직수정
  src/main/java/com/est/gongmoja/controller/UserController.java
  src/main/java/com/est/gongmoja/exception/ErrorCode.java
  src/main/java/com/est/gongmoja/service/UserService.java
Labels: 🔁refactor
